# Generated by Django 5.2.6 on 2026-08-30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presentations", "0007_coursesession_description_coursesession_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="offering_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONLINE_PRESENTATION", "Online presentation"),
                    ("OFFLINE_PRESENTATION", "Offline presentation"),
                    ("IN_PERSON_WORKSHOP", "In-person workshop"),
                    ("ONLINE_WORKSHOP", "Online workshop"),
                ],
                db_index=True,
                help_text="Blank values are retained only for legacy offerings.",
                max_length=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Leave blank for unlimited capacity.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legacy bundle composition; new package purchases are disabled.",
                related_name="parents",
                to="presentations.course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Price in Toman (IRT).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Price snapshot in Toman (IRT).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
