# Generated by Django 5.2.6 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentations", "0009_registration_waitlist_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="bundle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALL_ONLINE_PRESENTATIONS", "All online presentations"),
                    ("ALL_IN_PERSON_WORKSHOPS", "All in-person workshops"),
                    ("ALL_ONLINE_WORKSHOPS", "All online workshops"),
                ],
                db_index=True,
                help_text="Stable product type for current all-access bundle parents.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Current bundle composition. RegistrationItem preserves the "
                    "purchased composition historically."
                ),
                related_name="parents",
                to="presentations.course",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="presentations.course",
            ),
        ),
    ]
